CC = clang
CFLAGS = -Wall -Wextra -Werror -pedantic -std=c23
DEBUGFLAGS = -ggdb3 -Og
RELEASEFLAGS = -O3

c_files = $(wildcard src/*.c)
h_files = $(wildcard src/*.h)

debug_obj_files = $(patsubst src/%.c, build/debug/%.o, $(c_files))
release_obj_files = $(patsubst src/%.c, build/release/%.o, $(c_files))

build = build
debug = build/debug
release = build/release

ifeq ($(OS),Windows_NT)
	target = heap_alloc.exe
else
	target = heap_alloc
endif

debug: $(debug) $(debug_obj_files)
	$(CC) $(CFLAGS) $(DEBUGFLAGS) $(debug_obj_files) -o $(debug)/$(target)

release: $(release) $(release_obj_files)
	$(CC) $(CFLAGS) $(RELEASEFLAGS) $(release_obj_files) -o $(release)/$(target)

build/debug/%.o: src/%.c $(h_files)
	$(CC) $(CFLAGS) -c $< -o $@

build/release/%.o: src/%.c $(h_files)
	$(CC) $(CFLAGS) -c $< -o $@

.PHONY: clean
clean:
	rm -fr "$(build)"

$(debug): $(build)
	mkdir "$(debug)"

$(release): $(build)
	mkdir "$(release)"

$(build):
	mkdir "$(build)"