CC = clang
CFLAGS = -Wall -Wextra -Werror -pedantic -std=c23
DEBUGFLAGS = -ggdb3 -Og
RELEASEFLAGS = -O3

c_files = $(wildcard src/*.c)
h_files = $(wildcard src/*.h)

build = build
debug = build/debug
release = build/release

ifeq ($(OS),Windows_NT)
	target = heap_alloc.exe
else
	target = heap_alloc
endif

debug: $(c_files) $(h_files) | $(debug)
	$(CC) $(CFLAGS) $(DEBUGFLAGS) $(c_files) -o $(debug)/$(target)

release: $(c_files) $(h_files) | $(release)
	$(CC) $(CFLAGS) $(RELEASEFLAGS) $(c_files) -o $(release)/$(target)

.PHONY: clean
clean:
	rm -fr "$(build)"

$(debug): $(build)
	mkdir "$(debug)"

$(release): $(build)
	mkdir "$(release)"

$(build):
	mkdir "$(build)"