CC = clang
CFLAGS = -Wall -Wextra -Werror -pedantic -std=c23
DEBUGFLAGS = -ggdb3 -Og
RELEASEFLAGS = -O3

c_files = src/main.c src/heap.c
h_files = src/heap.h

build = build
debug = build/debug
release = build/release

target = heap_alloc.exe

.PHONY: debug release clean
debug: $(c_files) $(h_files) | $(debug)
	$(CC) $(CFLAGS) $(DEBUGFLAGS) $(c_files) -o $(debug)/$(target)

release: $(c_files) $(h_files) | $(release)
	$(CC) $(CFLAGS) $(RELEASEFLAGS) $(c_files) -o $(release)/$(target)

clean:
	rm -fr "$(build)"

$(debug): $(build)
	mkdir "$(debug)"

$(release): $(build)
	mkdir "$(release)"

$(build):
	mkdir "$(build)"