CPP = clang++
CPPFLAGS = -Wall -Wextra -Werror -pedantic -std=c++23
DEBUGFLAGS = -ggdb3 -Og
RELEASEFLAGS = -O3

cpp_files = $(wildcard src/*.cpp)
hpp_files = $(wildcard src/*.hpp src/*.inl)

debug_obj_files = $(patsubst src/%.cpp, build/debug/%.o, $(cpp_files))
release_obj_files = $(patsubst src/%.cpp, build/release/%.o, $(cpp_files))

build = build
debug = build/debug
release = build/release

ifeq ($(OS),Windows_NT)
	target = vector.exe
else
	target = vector
endif

debug: $(debug) $(debug_obj_files)
	$(CPP) $(CPPFLAGS) $(DEBUGFLAGS) $(debug_obj_files) -o $(debug)/$(target)

release: $(release) $(release_obj_files)
	$(CPP) $(CPPFLAGS) $(RELEASEFLAGS) $(release_obj_files) -o $(release)/$(target)

build/debug/%.o: src/%.cpp $(hpp_files)
	$(CPP) $(CPPFLAGS) -c $< -o $@

build/release/%.o: src/%.cpp $(hpp_files)
	$(CPP) $(CPPFLAGS) -c $< -o $@

.PHONY: clean
clean:
	rm -fr "$(build)"

$(debug): $(build)
	mkdir "$(debug)"

$(release): $(build)
	mkdir "$(release)"

$(build):
	mkdir "$(build)"