CPP = clang++
CPPFLAGS = -Wall -Wextra -Werror -pedantic -std=c++23
DEBUGFLAGS = -ggdb3 -Og
RELEASEFLAGS = -O3

cpp_files = src/main.cpp src/vector.cpp
hpp_files = src/vector.hpp src/vector.inl

build = build
debug = build/debug
release = build/release

target = vector.exe

.PHONY: debug release clean
debug: $(cpp_files) $(hpp_files) | $(debug)
	$(CPP) $(CPPFLAGS) $(DEBUGFLAGS) $(cpp_files) -o $(debug)/$(target)

release: $(cpp_files) $(hpp_files) | $(release)
	$(CPP) $(CPPFLAGS) $(RELEASEFLAGS) $(cpp_files) -o $(release)/$(target)

clean:
	rm -fr "$(build)"

$(debug): $(build)
	mkdir "$(debug)"

$(release): $(build)
	mkdir "$(release)"

$(build):
	mkdir "$(build)"