CPP = clang++
CPPFLAGS = -Wall -Wextra -Werror -pedantic -std=c++23
DEBUGFLAGS = -ggdb3 -Og
RELEASEFLAGS = -O3

cpp_files = $(wildcard src/*.cpp)
hpp_files = $(wildcard src/*.hpp src/*.inl)
data_files = $(wildcard *.txt)

build = build
debug = build/debug
release = build/release

ifeq ($(OS),Windows_NT)
	target = hashmap.exe
else
	target = hashmap
endif

debug: $(cpp_files) $(hpp_files) | $(debug)
	$(CPP) $(CPPFLAGS) $(DEBUGFLAGS) $(cpp_files) -o $(debug)/$(target)
	cp -f "$(data_files)" $(debug)

release: $(cpp_files) $(hpp_files) | $(release)
	$(CPP) $(CPPFLAGS) $(RELEASEFLAGS) $(cpp_files) -o $(release)/$(target)
	cp -f "$(data_files)" $(release)

.PHONY: clean
clean:
	rm -fr "$(build)"

$(debug): $(build)
	mkdir "$(debug)"

$(release): $(build)
	mkdir "$(release)"

$(build):
	mkdir "$(build)"