CPP = clang++
CPPFLAGS = -Wall -Wextra -Werror -pedantic -std=c++23
DEBUGFLAGS = -ggdb3 -Og
RELEASEFLAGS = -O3

cpp_files = src/main.cpp src/hashmap.cpp
hpp_files = src/hashmap.hpp src/hashmap.inl 
data_files = shakespeare.txt

build = build
debug = build/debug
release = build/release

target = hashmap.exe

.PHONY: debug release clean
debug: $(cpp_files) $(hpp_files) | $(debug)
	$(CPP) $(CPPFLAGS) $(DEBUGFLAGS) $(cpp_files) -o $(debug)/$(target)
	cp -f "$(data_files)" $(debug)

release: $(cpp_files) $(hpp_files) | $(release)
	$(CPP) $(CPPFLAGS) $(RELEASEFLAGS) $(cpp_files) -o $(release)/$(target)
	cp -f "$(data_files)" $(release)

clean:
	rm -fr "$(build)"

$(debug): $(build)
	mkdir "$(debug)"

$(release): $(build)
	mkdir "$(release)"

$(build):
	mkdir "$(build)"